// app/gui/src/dashboard/pages/authentication/LoadingScreen.tsx
/** @file A loading screen, displayed while the user is logging in. */
import { StatelessSpinner } from '#/components/StatelessSpinner'
import { Text } from '#/components/Text'
import { useText } from '$/providers/react'

/** The diameter of the spinner. */
const SPINNER_SIZE_PX = 64

/** A loading screen. */
export default function LoadingScreen() {
  const { getText } = useText()

  return (
    <div
      className="grid h-screen w-screen place-items-center text-primary"
      data-testid="loading-screen"
    >
      <div className="flex flex-col items-center gap-8 text-center">
        <StatelessSpinner phase="loading-fast" size={SPINNER_SIZE_PX} />

        <Text.Heading variant="h1" color="inherit">
          {getText('loadingAppMessage')}
        </Text.Heading>
      </div>
    </div>
  )
}

// app/gui/src/components/LoadingScreen.vue
<script setup lang="ts">
import { useText } from '$/providers/text'
import GrowingSpinner from '@/components/shared/GrowingSpinner.vue'
import { computed } from 'vue'

const SPINNER_SIZE_PX = 64

const text = useText()
const message = computed(() => text.getText('loadingAppMessage'))
</script>

<template>
  <div
    className="grid h-screen w-screen place-items-center text-primary"
    data-testid="loading-screen"
  >
    <div className="flex flex-col items-center gap-8 text-center">
      <GrowingSpinner phase="loading-fast" :size="SPINNER_SIZE_PX" />
      <h1 class="message" v-text="message" />
    </div>
  </div>
</template>

<style scoped>
.message {
  line-height: 29px;
  font-weight: 700;
  font-size: 19px;
}
</style>
