// app/ide-desktop/lib/dashboard/src/pages/authentication/LoadingScreen.tsx
/** @file A loading screen, displayed while the user is logging in. */
import * as React from 'react'

import * as textProvider from '#/providers/TextProvider'

import StatelessSpinner, * as statelessSpinner from '#/components/StatelessSpinner'

// =================
// === Constants ===
// =================

/** The diameter of the spinner. */
const SPINNER_SIZE_PX = 64

// =====================
// === LoadingScreen ===
// =====================

/** A loading screen. */
export default function LoadingScreen() {
  const { getText } = textProvider.useText()
  return (
    <div className="grid place-items-center text-primary h-screen w-screen">
      <div className="flex flex-col gap-4 items-center">
        <StatelessSpinner
          state={statelessSpinner.SpinnerState.loadingMedium}
          size={SPINNER_SIZE_PX}
        />
        <span>{getText('loadingAppMessage')}</span>
      </div>
    </div>
  )
}

// app/gui/src/components/LoadingScreen.vue
<script setup lang="ts">
import { useText } from '$/providers/text'
import GrowingSpinner from '@/components/shared/GrowingSpinner.vue'
import { computed } from 'vue'

const SPINNER_SIZE_PX = 64

const text = useText()
const message = computed(() => text.getText('loadingAppMessage'))
</script>

<template>
  <div
    className="grid h-screen w-screen place-items-center text-primary"
    data-testid="loading-screen"
  >
    <div className="flex flex-col items-center gap-8 text-center">
      <GrowingSpinner phase="loading-fast" :size="SPINNER_SIZE_PX" />
      <h1 class="message" v-text="message" />
    </div>
  </div>
</template>

<style scoped>
.message {
  line-height: 29px;
  font-weight: 700;
  font-size: 19px;
}
</style>
